
name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Check directory structure
      run: |
        pwd
        ls -la
        find . -name "package.json" -type f
      working-directory: ${{ github.workspace }}

    - name: Install Dependencies
      run: npm ci || npm install
      working-directory: ${{ github.workspace }}

    - name: Check package.json location
      run: ls -la && pwd && echo "Current directory is $(pwd)"
      working-directory: ${{ github.workspace }}

    - name: Build
      run: |
        npm run build || npx webpack --config webpack.config.js
      working-directory: ${{ github.workspace }}

    - name: Test
      run: |
        npm test || echo "No tests specified"
      working-directory: ${{ github.workspace }}
