
name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Debug environment
      run: |
        pwd
        ls -la
        find . -name "package.json" -type f
        echo "Current working directory: $(pwd)"
        echo "GitHub workspace: ${{ github.workspace }}"
      working-directory: ${{ github.workspace }}

    - name: Create package.json symlink for /dev-server if needed
      run: |
        if [ ! -d "/dev-server" ]; then
          sudo mkdir -p /dev-server
        fi
        if [ ! -f "/dev-server/package.json" ] && [ -f "${{ github.workspace }}/package.json" ]; then
          sudo cp ${{ github.workspace }}/package.json /dev-server/package.json
          echo "Created package.json symlink in /dev-server"
        fi
      working-directory: ${{ github.workspace }}

    - name: Install Dependencies
      run: npm ci || npm install
      working-directory: ${{ github.workspace }}

    - name: Build
      run: |
        npm run build || npx webpack --config webpack.config.js
      working-directory: ${{ github.workspace }}

    - name: Test
      run: |
        npm test || echo "No tests specified"
      working-directory: ${{ github.workspace }}
